### ISSUE TITLE
Moving the [file] component to the esphome?

### ISSUE THREAD

**Issue by honza73** [jesserockz/esphome-components#3]
I think it would be nice if your file component was a native esphome component (and had documentation directly on esphome.io). Then the https://esphome.io/guides/audio_clips_for_i2s guide would lose its usefulness and could be removed.

**Comment by jesserockz** [comment]
I do plan to move it into ESPHome. I built this randomly for some testing, not expecting it to actually be used by people.

**Comment by honza73** [comment]
Well... I think, If it is used in the official firmware (I mean https://github.com/esphome/firmware), one must suppose, that people will start using it.
:-)

Anyway, thanks for your response.
